### ISSUE TITLE
Unescaped expressions

### ISSUE THREAD

**Issue by masda70** [patientslikeme/emblem2hbs#3]
Emblem.js compiles two `=` into Handlebars triple-stash expressions
``==``  -> ``{{{}}}``
 
Currently, these are being converted to ``{{}}``

**Comment by nbudin** [comment]
Thanks for the bug report!  I've just released version 1.1.1, which fixes this.

**Comment by nbudin** [comment]
Actually, it seems that hasn't fully fixed the issue, as the indentation processor will turn the triple-stache back into a double stache.  Reopening and attempting the other half of the fix.

**Comment by nbudin** [comment]
OK, think I've got this one nailed down this time.  Version 1.1.2 released.  Sorry for the churn.
