### ISSUE TITLE
Get error when trying to convert file

### ISSUE THREAD

**Issue by brandonjmckay** [patientslikeme/emblem2hbs#4]
All I get when running `emblem2hbs index.emblem` on my emblem file is:

```
env: coffee: No such file or directory
```

**Comment by nbudin** [comment]
Does doing `npm install -g coffee-script` help?

**Comment by okize** [comment]
https://github.com/patientslikeme/emblem2hbs/pull/6 should fix this issue.

**Comment by nbudin** [comment]
@okize's fix is now released in version 1.1.3.
